### ISSUE TITLE
Broken import declaration during build

### ISSUE THREAD

**Issue by aheinricy** [davinkevin/Podcast-Server#106]
I'm trying to build Podcast-Server for the first time and I'm receiving the following error during build. 

```
[INFO] [15:39:49] Starting 'build'...
[INFO] [15:39:49] Starting 'build:create-folder'...
[INFO] [15:39:49] Finished 'build:create-folder' after 1.58 ms
[INFO] [15:39:49] Starting 'build:pre-clean'...
[INFO] [15:39:50] Finished 'build:pre-clean' after 9.62 ms
[INFO] [15:39:50] Starting 'build:jspm'...
[INFO] [15:40:02] 'build:jspm' errored after 12 s
[INFO] [15:40:02] Error: Error: CSS Plugin:
[INFO] Broken @import declaration of "app/common/component/item-menu/item-menu.css"
[INFO] Broken @import declaration of "app/search/search.css"
[INFO] Broken @import declaration of "app/podcasts/podcasts.css"
[INFO] Broken @import declaration of "app/common/component/watchlist-chooser/watchlist-chooser.css"
[INFO] Broken @import declaration of "app/player/player.css"
[INFO] Broken @import declaration of "app/config/bootstrap/bootstrap.css"
[INFO] Broken @import declaration of "app/common/component/videogular/vg-copy/vg-copy.css"
[INFO] Broken @import declaration of "app/common/component/videogular/vg-link/vg-link.css"
[INFO] Broken @import declaration of "app/common/component/videogular/videogular.css"
[INFO] Broken @import declaration of "app/common/component/player-inline/player-inline.css"
[INFO] Broken @import declaration of "app/common/component/navbar/navbar.css"
[INFO] Broken @import declaration of "app/common/component/updating/updating.css"
[INFO] Broken @import declaration of "app/config/font-awesome/font-awesome.css"
[INFO] Broken @import declaration of "app/config/ionicons/ionicons.css"
[INFO] Broken @import declaration of "app/config/styles/bootstrap-adaptation.css"
[INFO] Broken @import declaration of "app/config/styles/podcastserver.css"
[INFO] Broken @import declaration of "app/config/styles/tags-input-bootstrap.css"
[INFO]     at /opt/Podcast-Server/frontend-angularjs/gulp/tasks/build.js:30:27
[INFO]     at tryCatcher (/opt/Podcast-Server/frontend-angularjs/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/util.js:16:23)
[INFO]     at Promise._settlePromiseFromHandler (/opt/Podcast-Server/frontend-angularjs/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:512:31)
[INFO]     at Promise._settlePromise (/opt/Podcast-Server/frontend-angularjs/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:569:18)
[INFO]     at Promise._settlePromise0 (/opt/Podcast-Server/frontend-angularjs/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:614:10)
[INFO]     at Promise._settlePromises (/opt/Podcast-Server/frontend-angularjs/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:689:18)
[INFO]     at Async._drainQueue (/opt/Podcast-Server/frontend-angularjs/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/async.js:133:16)
[INFO]     at Async._drainQueues (/opt/Podcast-Server/frontend-angularjs/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/async.js:143:10)
[INFO]     at Immediate.Async.drainQueues [as _onImmediate] (/opt/Podcast-Server/frontend-angularjs/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/async.js:17:14)
[INFO]     at tryOnImmediate (timers.js:543:15)
[INFO]     at processImmediate [as _immediateCallback] (timers.js:523:5)
[INFO] [15:40:02] 'build' errored after 12 s
[INFO] [15:40:02] Error in plugin 'run-sequence(build:jspm)'
[INFO] Message:
[INFO]     Error: CSS Plugin:
[INFO] Broken @import declaration of "app/common/component/item-menu/item-menu.css"
[INFO] Broken @import declaration of "app/search/search.css"
[INFO] Broken @import declaration of "app/podcasts/podcasts.css"
[INFO] Broken @import declaration of "app/common/component/watchlist-chooser/watchlist-chooser.css"
[INFO] Broken @import declaration of "app/player/player.css"
[INFO] Broken @import declaration of "app/config/bootstrap/bootstrap.css"
[INFO] Broken @import declaration of "app/common/component/videogular/vg-copy/vg-copy.css"
[INFO] Broken @import declaration of "app/common/component/videogular/vg-link/vg-link.css"
[INFO] Broken @import declaration of "app/common/component/videogular/videogular.css"
[INFO] Broken @import declaration of "app/common/component/player-inline/player-inline.css"
[INFO] Broken @import declaration of "app/common/component/navbar/navbar.css"
[INFO] Broken @import declaration of "app/common/component/updating/updating.css"
[INFO] Broken @import declaration of "app/config/font-awesome/font-awesome.css"
[INFO] Broken @import declaration of "app/config/ionicons/ionicons.css"
[INFO] Broken @import declaration of "app/config/styles/bootstrap-adaptation.css"
[INFO] Broken @import declaration of "app/config/styles/podcastserver.css"
[INFO] Broken @import declaration of "app/config/styles/tags-input-bootstrap.css"
[INFO] Stack:
[INFO] Error: Error: CSS Plugin:
[INFO] Broken @import declaration of "app/common/component/item-menu/item-menu.css"
[INFO] Broken @import declaration of "app/search/search.css"
[INFO] Broken @import declaration of "app/podcasts/podcasts.css"
[INFO] Broken @import declaration of "app/common/component/watchlist-chooser/watchlist-chooser.css"
[INFO] Broken @import declaration of "app/player/player.css"
[INFO] Broken @import declaration of "app/config/bootstrap/bootstrap.css"
[INFO] Broken @import declaration of "app/common/component/videogular/vg-copy/vg-copy.css"
[INFO] Broken @import declaration of "app/common/component/videogular/vg-link/vg-link.css"
[INFO] Broken @import declaration of "app/common/component/videogular/videogular.css"
[INFO] Broken @import declaration of "app/common/component/player-inline/player-inline.css"
[INFO] Broken @import declaration of "app/common/component/navbar/navbar.css"
[INFO] Broken @import declaration of "app/common/component/updating/updating.css"
[INFO] Broken @import declaration of "app/config/font-awesome/font-awesome.css"
[INFO] Broken @import declaration of "app/config/ionicons/ionicons.css"
[INFO] Broken @import declaration of "app/config/styles/bootstrap-adaptation.css"
[INFO] Broken @import declaration of "app/config/styles/podcastserver.css"
[INFO] Broken @import declaration of "app/config/styles/tags-input-bootstrap.css"
[INFO]     at /opt/Podcast-Server/frontend-angularjs/gulp/tasks/build.js:30:27
[INFO]     at tryCatcher (/opt/Podcast-Server/frontend-angularjs/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/util.js:16:23)
[INFO]     at Promise._settlePromiseFromHandler (/opt/Podcast-Server/frontend-angularjs/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:512:31)
[INFO]     at Promise._settlePromise (/opt/Podcast-Server/frontend-angularjs/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:569:18)
[INFO]     at Promise._settlePromise0 (/opt/Podcast-Server/frontend-angularjs/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:614:10)
[INFO]     at Promise._settlePromises (/opt/Podcast-Server/frontend-angularjs/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/promise.js:689:18)
[INFO]     at Async._drainQueue (/opt/Podcast-Server/frontend-angularjs/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/async.js:133:16)
[INFO]     at Async._drainQueues (/opt/Podcast-Server/frontend-angularjs/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/async.js:143:10)
[INFO]     at Immediate.Async.drainQueues [as _onImmediate] (/opt/Podcast-Server/frontend-angularjs/node_modules/jspm/node_modules/systemjs-builder/node_modules/bluebird/js/release/async.js:17:14)
[INFO]     at tryOnImmediate (timers.js:543:15)
[INFO]     at processImmediate [as _immediateCallback] (timers.js:523:5)
[ERROR]
[ERROR] npm ERR! Linux 4.4.0-130-generic
[ERROR] npm ERR! argv "/opt/Podcast-Server/frontend-angularjs/target/node/node" "/opt/Podcast-Server/frontend-angularjs/target/node/node_modules/npm/bin/npm-cli.js" "run" "build"
[ERROR] npm ERR! node v6.2.0
[ERROR] npm ERR! npm  v2.15.6
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! Podcast_Server@2018.7.0 build: `gulp build`
```

This is preventing me from completing the build. Any idea what is causing the build to fail?

**Comment by davinkevin** [comment]
Do you have any error prior to this one?

I'm seeing multiple problems those days on Travis-CI about github token and JSPM. 

The angularjs version isn't under development anymore, so I should find a solution in order to simplify this part of the build. 

Instead of building it, you can use the docker images published each month on the [docker-hub](https://hub.docker.com/r/davinkevin/podcast-server/tags/).
