### ISSUE TITLE
Error during signature of podcast at url

### ISSUE THREAD

**Issue by Gomez** [davinkevin/Podcast-Server#93]
I installed the docker version and get this error when adding a podcast (sorry, formatting as code does not work) :

```
2018-03-24 20:50:07.850 ERROR 1 --- [Manual-Update-1] l.d.p.service.SignatureService           : Error during signature of podcast at url http://feeds.soundcloud.com/users/soundcloud:users:21436304/sounds.rss

java.lang.RuntimeException: Error during creation of stream
        at lan.dk.podcastserver.service.UrlService.lambda$asStream$3(UrlService.java:97) ~[classes!/:1.1.0-SNAPSHOT]
        at io.vavr.control.Try.getOrElseThrow(Try.java:684) ~[vavr-0.9.1.jar!/:na]
        at lan.dk.podcastserver.service.UrlService.asStream(UrlService.java:97) ~[classes!/:1.1.0-SNAPSHOT]
        at lan.dk.podcastserver.service.UrlService.asReader(UrlService.java:101) ~[classes!/:1.1.0-SNAPSHOT]
        at lan.dk.podcastserver.service.SignatureService.lambda$generateSignatureFromURL$d58c5039$1(SignatureService.java:26) ~[classes!/:1.1.0-SNAPSHOT]
        at io.vavr.control.Try$WithResources1.lambda$of$97fea75d$1(Try.java:1202) ~[vavr-0.9.1.jar!/:na]
        at io.vavr.control.Try.of(Try.java:75) ~[vavr-0.9.1.jar!/:na]
        at io.vavr.control.Try$WithResources1.of(Try.java:1201) ~[vavr-0.9.1.jar!/:na]
        at lan.dk.podcastserver.service.SignatureService.generateSignatureFromURL(SignatureService.java:27) ~[classes!/:1.1.0-SNAPSHOT]
        at lan.dk.podcastserver.manager.worker.rss.RSSUpdater.signatureOf(RSSUpdater.java:108) ~[classes!/:1.1.0-SNAPSHOT]
        at lan.dk.podcastserver.manager.worker.Updater.lambda$update$b212c4f7$1(Updater.java:23) ~[classes!/:1.1.0-SNAPSHOT]
        at io.vavr.control.Try.of(Try.java:75) ~[vavr-0.9.1.jar!/:na]
        at io.vavr.API.Try(API.java:917) ~[vavr-0.9.1.jar!/:na]
        at lan.dk.podcastserver.manager.worker.Updater.update(Updater.java:23) ~[classes!/:1.1.0-SNAPSHOT]
        at lan.dk.podcastserver.business.update.UpdatePodcastBusiness.lambda$null$0(UpdatePodcastBusiness.java:104) ~[classes!/:1.1.0-SNAPSHOT]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_161]
Caused by: com.mashape.unirest.http.exceptions.UnirestException: java.net.UnknownHostException: feeds.soundcloud.com
        at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143) ~[unirest-java-1.4.9.jar!/:na]
        at com.mashape.unirest.request.BaseRequest.asBinary(BaseRequest.java:92) ~[unirest-java-1.4.9.jar!/:na]
        at io.vavr.control.Try.mapTry(Try.java:616) ~[vavr-0.9.1.jar!/:na]
        at lan.dk.podcastserver.service.UrlService.asStream(UrlService.java:95) ~[classes!/:1.1.0-SNAPSHOT]
        ... 16 common frames omitted
Caused by: java.net.UnknownHostException: feeds.soundcloud.com
        at java.net.InetAddress.getAllByName0(InetAddress.java:1280) ~[na:1.8.0_161]
        at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[na:1.8.0_161]
        at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[na:1.8.0_161]
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[httpclient-4.5.5.jar!/:4.5.5]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112) ~[httpclient-4.5.5.jar!/:4.5.5]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373) ~[httpclient-4.5.5.jar!/:4.5.5]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.5.jar!/:4.5.5]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.5.jar!/:4.5.5]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.5.jar!/:4.5.5]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.5.jar!/:4.5.5]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[httpclient-4.5.5.jar!/:4.5.5]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.5.jar!/:4.5.5]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.5.jar!/:4.5.5]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.5.jar!/:4.5.5]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.5.jar!/:4.5.5]
        at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:138) ~[unirest-java-1.4.9.jar!/:na]
        ... 19 common frames omitted
```

**Comment by davinkevin** [comment]
Could you provide the url you use ? I will try to reproduce and fix it .

**Comment by Gomez** [comment]
http://feeds.soundcloud.com/users/soundcloud:users:21436304/sounds.rss

(hidden because of the formatting)

**Comment by davinkevin** [comment]
This is working well on the dev version.

<img width="1594" alt="capture d ecran 2018-03-25 a 15 14 35" src="https://user-images.githubusercontent.com/1970922/37875426-468d1f04-303f-11e8-90c6-04b899f03fae.png">

The error you have posted show an `UnknownHostException` which is the result of the lack of DNS entry for the host `feeds.soundcloud.com`. 

Is it your first podcast in the application? Does the application has access to a dns server ?

**Comment by Gomez** [comment]
You are right. --dns <DNS SERVER> fixed it. Thanks!
